language: cpp
os: linux
dist: bionic
compiler: gcc

script: ./build.sh

deploy:
    provider: script
    skip_cleanup: true
    script:
    - curl -T HelloWorld-0.1.$TRAVIS_BUILD_NUMBER-Linux.deb -alexeyya:$BINTRAY_KEY "https://api.bintray.com/content/alexeyya/helloworld/origin/$TRAVIS_BUILD_NUMBER/HelloWorld-0.1.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
