version: '0.1.{build}'

image: Visual Studio 2017

platform:
  - x64

configuration:
  - Release
  - Debug

before_build:
    - cmake -G "Visual Studio 15 2017 Win64" .

build:
  project: $(APPVEYOR_BUILD_FOLDER)\helloworld.sln

test_script:
  - '%APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\tests.exe'

deploy:
- provider: BinTray
  username: alexeyya
  api_key:
    secure: AxjYJbTd/GAJNYnkV6NpQoxE8JKQbHBT0ZfCa5kg2MvJObnYw7XYQq8EZ+wAjjrn
  subject: alexeyya
  repo: helloworld
  package: origin
  publish: true
  override: true
  explode: true
  